# Generated by Django 5.1.1 on 2024-09-25 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Done')], default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Done'), (2, 'Postponed')], default=0),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Done'), (2, 'Postponed')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Done'), (2, 'Postponed')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='Boards.label'),
        ),
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('MEMBER', 'Member'), ('VISITOR', 'Visitor')], max_length=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Boards.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('board', 'user')},
            },
        ),
    ]
